apiVersion: v1
kind: Pod
metadata:
  name: my-custom-pod
spec:
  containers:
     - name: my-pod-container1
       image: hello-world
       ports:
         - name: http
           containerPort: 80
           protocol: TCP

